export enum Routes {
    home = 'home',
    confrontation = 'confrontation',
    tickets = 'tickets',
    profile = 'profile',
    login = 'login',
    language = 'language',
    onboarding = 'onboarding',
    register = 'register',
    forgot = 'forgot',
    otp = 'otp',
    reset='reset',
    loginasan='loginasan',
    loginemail='loginemail',
    waiting = 'waiting',
    detail='detail',
    order='order',
    paymnet='payment',
    notfication='notfication',
    notficationDetail='notficationDetail',
}